@baseUrl = http://localhost:3000

# @name create_schema
POST {{baseUrl}}/schema
Content-Type: application/json

{
	"title": "title name",
	"description": "",
	"creatorId": "325c1ae6-21f9-4dca-91cc-b9cddf7b590f",
	"data": {
		"type": "object",
		"properties": {
			"name": {
				"type": "string"
			},
			"age": {
				"type": "number"
			}
		}
	}
}

###

# @name register_user
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
	"name": "user name",
	"email": "user@user4.com",
	"password": "123456"
}
