@baseUrl = http://localhost:3000
@user_id = {{register_user.response.body.user._id.value}}

# @name create_schema
POST {{baseUrl}}/schema
Content-Type: application/json

{
	"title": "title name",
	"description": "",
	"creatorId": "{{user_id}}",
	"data": {
		"type": "object",
		"properties": {
			"name": {
				"type": "string"
			},
			"age": {
				"type": "number"
			}
		}
	}
}

###

# @name register_user
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
	"name": "user name",
	"email": "user@user.com",
	"password": "123456"
}
