version: '3.8'

services:
  postgres:
    container_name: variant-lists-pg
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: variant-lists
      PGDATA: /data/postgres
