import { Londrina_Solid } from "next/font/google";

import type { Metadata } from "next";
import "./globals.css";
import { Card } from "@/components/ui/card";

const londrinaSolid = Londrina_Solid({
	weight: ["100", "300", "400", "900"],
	subsets: ["latin"],
	variable: "--font-londrina-solid",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${londrinaSolid.variable}`}>
			<body
				className={`antialiased h-screen w-screen flex justify-center items-center`}
			>
				<Card className="h-[80vh] border-4 rounded-2xl border-black drop-shadow-hard pt-28 px-8">
					{children}
				</Card>
			</body>
		</html>
	);
}
