name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: 'postgres://postgres:docker@localhost:5432/variant-lists?schema=public'
      PORT: '3001'
      HOST: '127.0.0.1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
        echo "PORT=$PORT" >> $GITHUB_ENV
        echo "PORT=$PORT" >> $GITHUB_ENV

    - name: Enter in packages
      run: cd packages/domain

    - name: Run tests
      run: yarn test