name: Run Tests

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

  test:
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
    - name: Run tests
      run: yarn test

  test-integration:
    runs-on: ubuntu-latest
    needs: setup

    env:
      DATABASE_URL: 'postgres://postgres:docker@localhost:5432/variant-lists?schema=public'
      PORT: '3001'
      HOST: '127.0.0.1'

    steps:
    - name: Build packages
      run: yarn build

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: sleep 5

    - name: Run tests
      run: yarn test:integration

    - name: Shut down Docker Compose
      if: always()
      run: docker-compose down
