name: Run Integration Tests

on: [pull_request]

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: yarn

            - name: Run tests
              run: yarn test

    integration-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: yarn

            - name: Install Docker Compose
              run: sudo apt-get update && sudo apt-get install -y docker-compose

            - name: Set up Docker Compose
              run: docker-compose up -d

            - name: Wait for services to be ready
              run: sleep 5

            - name: Run integration tests
              run: yarn test:integration
              env:
                  DATABASE_URL: "postgres://postgres:docker@localhost:5432/variant-lists?schema=public"
                  PORT: "3001"
                  HOST: "127.0.0.1"
                  JWT_REFRESH_SECRET: "secret"
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}

            - name: Shut down Docker Compose
              if: always()
              run: docker-compose down
